/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package senderbot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class SenderBotApplication {

    public static void main(String[] args) {
        SpringApplication.run(SenderBotApplication.class, args);
    }
}
